### ISSUE TITLE
consistent gen_server call timeouts

### ISSUE THREAD

**Issue by mritalian** [pgourlain/vscode_erlang#100]
When I enable verbose, I consistently see gen_server timeouts in the log like so:

```
using erlang binaries from path : 'C:/Program Files/erl10.0/bin/'
starting : erlc 
-o ../ebin vscode_lsp_entry.erl
erlc exit code:0
using erlang binaries from path : 'C:/Program Files/erl10.0/bin/'
starting : erl 
-noshell -pa src -pa ebin -s int -vscode_port 49983 -s vscode_lsp_entry start 49983 
erlc exit code:0
Old inliner: threshold=0 functions=[{hex,1}]
Old inliner: threshold=0 functions=[{object_key,2}]
=ERROR REPORT==== 29-Jun-2018::11:39:59.617000 ===
LSP handler error exit:{timeout,
                        {gen_server,call,
                         [gen_lsp_doc_server,
                          {set_document_attribute,
```

I see one **erl.exe** in task manager, that exits if I close vs code.

Other symptoms I see is that
- Almost always, it fails to lint the file (errors are not highlighted)
- When it does lint, it systematically fails to find my include files, no matter what I put in **erlang.includePaths**

I've tried different erlang versions, disabling firewall, rebooting, nothing seems to make a difference.  As it is now, the plugin is nothing but a glorified syntax highlighter.

**Comment by wojteksurowka** [comment]
@mritalian I cannot reproduce the problems you report. I can try to investigate, but for this I would need more information:
- does this behaviour depend on the project? Can you try with a very small project, and when you observe the same behaviour, share the project please
- are there any other errors in the log apart from timeouts
- do you observe any other erroneous behaviour with Erlang on your system
Thank you for your cooperation.

**Comment by mritalian** [comment]
Hello, thanks for the follow up.  I will be fair and admit that the repo in question is quite simply massive.  I have 25 submodules, each one is a library, and 20 other library dependencies I bring in through rebar.

If I use a small project it seems to lint.   On the large repo, if I just forget about it fo ra while, eventually it lints (red underline on things that it things are no good).

When it does work, however, this brings me to my other issue of **include_lib** not working, no matter what combination of paths I put in **erlang.includePaths**, either in workspace or global settings.

**Comment by wandermyz** [comment]
I'm also seeing this issue on a big complicated project. My extension works fine on a almost-empty project.
Is there a way to tweak this timeout ?
