### ISSUE TITLE
Add more settings to the code formatter

### ISSUE THREAD

**Issue by codeadict** [pgourlain/vscode_erlang#102]
First, thanks y'all for this great project. The actual code formatter causes some weird indentation like:

```erlang
change_config(Configs) ->
    case lists:keyfind(?APP, 1,
		       application:which_applications())
	of
      false ->
	  ok;
      _ ->
	  lager:debug("Reloading config ~p", [Configs])
    end.
```

I suspect this happens because it needs a setting for longer line lengths.

Is there any workaround for this or is indeed a limitation of this plugin?

**Comment by pgourlain** [comment]
Hi,

thanks for your report.

Right now, erl_tidy: format (file) is used to format document. there is no workaround as is. I should use http://erlang.org/doc/man/erl_prettypr.html#format-2 in next release to get more options for breaking line length limit

**Comment by codeadict** [comment]
Or having the option to format with emacs maybe?

**Comment by pselden** [comment]
There's a code formatter? How do I use it? 

Attempting to format the file leads to "There is no selection formatter for 'erlang'-files installed."

**Comment by pgourlain** [comment]
Hello

@pselden , yes there is a code formatter, but today only for whole file( remove selection before formating)

**Comment by fholzhauser** [comment]
Hi, Could you please reopen this one please ? I think the original request was for whole file formatting and is very relevant. Unfortunately the comment about selection formatting "hijacked" this useful feature request. Would it be possible to add the line lenght (paper/ribbon) configurable options to erl_prettypr:format ? And indeed thanks for your work on this great plugin !
