### ISSUE TITLE
Add OTP 21 Support

### ISSUE THREAD

**Issue by flash2307** [pgourlain/vscode_erlang#104]
New syntax from OTP 21 is not supported. For example, the new try/catch syntax allows to retrieve the stacktrace directly from the catch clause like that: 
```
try something() of
    Result -> ...
catch
    Class:Reason:Stacktrace -> ...
end
```
Here, `:Stacktrace` raise an `illegal pattern` error!

Thanks for the extension by the way!

**Comment by pgourlain** [comment]
Hi,

I use ErlangInstaller. when I switch to OTP 23.0. I didn't have this issue.

to check which version of erlang is use in the extension, activate trace in settings, then check the first line. it should be something like that
```
 using erlang binaries from path : '/Users/xxxx/Library/Application Support/ErlangInstaller/23.0/bin'
````

**Comment by zeek0x** [comment]
If you want to run OTP 21 or earlier, you can do so by reverting to an extension version.

- Get vsix.

```
curl -o erlang-0.6.3.vsix "https://pgourlain.gallery.vsassets.io/_apis/public/gallery/publisher/pgourlain/extension/erlang/0.6.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
```

- Open the command palette, type `vsix` and go to `Install from VSIX` to get Select `erlang-0.6.3.vsix`.
- To turn off automatic updates to the extension, set the following

setting.json
```
    "extensions.autoUpdate": false
```

**Comment by pgourlain** [comment]
Thanks, I will check with the OTP 21 runtime.

**Comment by pgourlain** [comment]
Hi, 

With 0.6.5, you can use until OTP 18.

can you check if it works for you ?

**Comment by zeek0x** [comment]
Hi 

I checked with 0.6.5, It's work!!!

Compile error seems to be a problem specific to 0.6.4.

BTW, I post the errors on the vscode's OUTPUT.

- Erlang/OTP: 20.3
- vscode_erlang: 0.6.4

```console
erlang extension is active
using erlang binaries from path : 'XXX/bin/erlang/20.3/bin'
starting : escript 
XXX/.vscode/extensions/pgourlain.erlang-0.6.4/rebar3 compile
[0;32m===> Verifying dependencies...
[0m[0;32m===> Compiling vscode_lsp
[0m
[0;31m===> [1mCompiling apps/erlangbridge/src/lsp_navigation.erl failed
[0m[0m
apps/erlangbridge/src/lsp_navigation.erl:44: illegal pattern
apps/erlangbridge/src/lsp_navigation.erl:45: variable 'M' is unbound
apps/erlangbridge/src/lsp_navigation.erl:45: variable 'STK' is unbound

escript exit code:1
using erlang binaries from path : 'XXX/bin/erlang/20.3/bin'
starting : erl 
-noshell -pa src -pa ebin -s int -vscode_port 62444 -s vscode_lsp_entry start 62444 
src/lsp_navigation.erl:44: illegal pattern
src/lsp_navigation.erl:45: variable 'M' is unbound
src/lsp_navigation.erl:45: variable 'STK' is unbound

=ERROR REPORT==== 2-Aug-2020::10:43:45 ===
compile result of "src/lsp_navigation": error

=ERROR REPORT==== 2-Aug-2020::10:43:45 ===
compile_needed_modules failed : error
```

Thanks for good extension!

**Comment by pgourlain** [comment]
Thanks for your report and tests !
