### ISSUE TITLE
env: escript: No such file or directory

### ISSUE THREAD

**Issue by ChuckIrvine** [pgourlain/vscode_erlang#108]
When I try to run "rebar compile"

![screen shot 2018-10-03 at 5 59 07 pm](https://user-images.githubusercontent.com/657002/46444112-150af080-c736-11e8-8a16-69efd86c9094.png)

The vscode output window shows:

![screen shot 2018-10-03 at 6 00 50 pm](https://user-images.githubusercontent.com/657002/46444160-4d123380-c736-11e8-9e21-59869dd4eb02.png)

My setting are:

![screen shot 2018-10-03 at 6 01 55 pm](https://user-images.githubusercontent.com/657002/46444177-6f0bb600-c736-11e8-92b8-45ba9121480e.png)

escript resides in /usr/local/bin as shown by:

![screen shot 2018-10-03 at 6 03 38 pm](https://user-images.githubusercontent.com/657002/46444230-af6b3400-c736-11e8-8e5c-f76f9380d6df.png)

Can someone help me understand what might be going wrong?

Thanks

**Comment by pgourlain** [comment]
Hi,

Did you test with another version of rebar ?

**Comment by pgourlain** [comment]
Closed du to no answer
