### ISSUE TITLE
Add outline view support

### ISSUE THREAD

**Issue by andreabenini** [pgourlain/vscode_erlang#109]
Newer vscode versions do have outline view support built in (https://code.visualstudio.com/docs/getstarted/userinterface#_explorer) . They have extended Outline with APIs for every language and there are even builtin supports for popular languages. Erlang is not mainstream so it should be added manually, is it possible to add a feature request for it ?

Thanks
Ben

**Comment by pgourlain** [comment]
Hi,

Thanks for your report
I will take a look on this feature.

**Comment by Zalastax** [comment]
This is done and can be closed, right?
