### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by seanwhill** [pgourlain/vscode_erlang#110]
Issue Type: <b>Bug</b>

Syntax Highlighting does not work.
I have tried changing the themes and uninstalling and reloading erlang extensions. I cant seem to get it to work

Extension version: 0.4.6
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by pgourlain** [comment]
Hi,

Thanks for your report. could you activate technical traces ? (in your user settings, search for erlang extension)

**Comment by fultonm** [comment]
I'm having the same issue. The document formatter also doesn't work "There is no document formatter for erlang-files installed"

I turned on technical traces and there is no output.
