### ISSUE TITLE
Support go to defiinition for Macro

### ISSUE THREAD

**Issue by m4ver1k** [pgourlain/vscode_erlang#120]
Hello,

Firstly thanks for this project, appreciate the time and effort that go in this. 

I'm requesting a feature  `go to definition for macros`.  

_I have no prior experience with language servers or vscode lang extensions, but I can try to chip in if someone can help me with this._

**Comment by mcmonkeys1** [comment]
bump +1 !

**Comment by wojteksurowka** [comment]
Fixed by #178

**Comment by shuying2244** [comment]
Hello,
`go to definition for macros` is wonderful.
But what if you can support like ?sql_ninja_too or ?wxID_ANY macro is even better.
Thank you for your efforts.
