### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by PatrickSachs** [pgourlain/vscode_erlang#122]
Hello there!

This is pretty much just a support request - I'm having trouble in actually getting my application to start using this extension.

I've created a minimal sample repo: https://github.com/PatrickSachs/erlang-vscode-test (no gitignore, every file included)

If I hit "F5" to run the app rebar3 compiles everything, but afterwards nothing else seems to happen. (Same if I directly click Launch in the debug window). The only thing different in my config is that I used `escript rebar3 compile` instead of `rebar3 compile` since rebar3 is not in my PATH.

If I type `./rebar3 shell` into my terminal the erlang application starts as desired.

_"Terminal" Output:_
```
> Executing task: escript rebar3 compile <

===> Verifying dependencies...
===> Compiling erlvscode

Terminal will be reused by tasks, press any key to close it.
```
_"Debug Console" Output:_
```
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:45581
erlc exit code:0
Starting erlang
	path      : /home/patrick/Development/erlang-vscode-test
	arguments : undefined
starting : erl 
-noshell -pa "/home/patrick/.vscode/extensions/pgourlain.erlang-0.5.0/apps/erlangbridge/ebin" -s int -vscode_port 45581 -s vscode_connection start -args_file "/tmp/erlang-vscode-test_3819153" 
erlang bridge listen on port :58909
```

No more output in other windows

Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

**Comment by pgourlain** [comment]
Hi,
Sorry for the delay, I only work on this extension on my free time....

can you test with arguments : 
"arguments": "-s application start erlvscode""
or 
"arguments": "-eval \"application:start(erlvscode)\""

set them in your "launch.config".

**Comment by Patrick-Sachs** [comment]
Sorry for my delay. I wasn't working with Erlang recently so I did not have time to look at it. Your last suggestions seems to work. I've only been able to test this on macOS, I'll test on my home Ubuntu PC as soon as possible.

https://github.com/PatrickSachs/erlang-vscode-test/pull/1

Thank you so much already! I'll close this once I can confirm it works on every OS.

**Comment by PatrickSachs** [comment]
Awesome - Works on Linux too. Thank you for your time.

This allows me to finally fully switch to VS Code for all languages I use.
