### ISSUE TITLE
Completion does not work in some cases

### ISSUE THREAD

**Issue by Yozhig** [pgourlain/vscode_erlang#128]
Completion does not work when file has not been edited and saved before (from launch of vscode to the moment). Call of `gen_lsp_doc_server:get_document_attribute/2` at https://github.com/pgourlain/vscode_erlang/blob/master/apps/erlangbridge/src/lsp_handlers.erl#L131 returns `undefined` and then `binary:split/3` throws `badarg`. My workaround for this is to call `gen_lsp_doc_server:set_document_attribute/3` at `textDocument_didOpen/2` handler:
```
textDocument_didOpen(Socket, Params) ->
    File = lsp_utils:file_uri_to_file(mapmapget(textDocument, uri, Params)),
    gen_lsp_doc_server:set_document_attribute(File, contents, mapmapget(textDocument, text, Params)),
    gen_lsp_config_server:autosave() andalso file_contents_update(Socket, File, undefined).
```

**Comment by pgourlain** [comment]
Hi,

Thanks for your report and contribution
