### ISSUE TITLE
Is there autocomplete support?

### ISSUE THREAD

**Issue by mrkaspa** [pgourlain/vscode_erlang#14]

**Comment by pgourlain** [comment]
Hi,

Today there is only "syntaxhighlighting", because language server (https://code.visualstudio.com/docs/extensions/example-language-server) is not yet implemented

**Comment by iambumblehead** [comment]
edts uses an erl service to provide auto-completion
https://github.com/tjarvstrand/edts/tree/master/lib/edts/src

edts is difficult to setup but works well once the setup is done. _maybe_ edts' service could be re-purposed for vscode?

**Comment by pgourlain** [comment]
Thanks for the link, and you right "The EDTS node exposes a REST-interface". I use the same technic. 
I should take a look....
