### ISSUE TITLE
Go to definition doesn't work from the export directive

### ISSUE THREAD

**Issue by martincox** [pgourlain/vscode_erlang#146]
Go to definition works within functions, locally and across modules. However, it does not seem to work from a function in the export directive. I'm not sure if this is a misconfiguration on my part, or a general issue.

Does anyone else have the same problem?

**Comment by wojteksurowka** [comment]
Fixed by #178

**Comment by shuying2244** [comment]
If I write it like this
    `-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2, code_change/3]).`
`go to definition` normal work.
But if I write it like this
```
-export([
    init/1              %% function description
    ,handle_call/3      %% function description
    ,handle_cast/2
    ,handle_info/2
    ,terminate/2
    ,code_change/3
]).
```
`go to definition` will doesn't work.
So, can you add support for the second way?Thank you very much.

**Comment by martincox** [comment]
Yep, I see the same behaviour as outlined by @shuying2244 

`-module(riak_kv_vnode).
-behaviour(riak_core_vnode).

%% API
-export([test_vnode/1, put/7]).
-export([start_vnode/1,
             start_vnodes/1
`

Both test_vnode/1 and put/7 work, start_vnode/1 also works, but when the functions are on a newline, goto definition won't work - so in the above example, start_vnodes/1 doesn't work. Seems like the newline is the issue?
