### ISSUE TITLE
Ability to exclude path from source analysis (to ignore eunit source copy)

### ISSUE THREAD

**Issue by Toons33** [pgourlain/vscode_erlang#147]
When running eunit suites, all sources are copied in the `.eunit` folder (for covering I guess). This causes "Go to definition"  to open the wrong source file (e.g. `.eunit/mod.erl` instead of `src/mod.erl`) -- I've been burned multiple times by this (I change the source *copy* in eunit folder, and my change has no impact. Worse even: if I run eunit again, the file I changed is written over and lost).

For that reason, it'd be great to be able to also have an `Exclude Paths` option (in addition to the existing `Include Paths` option).

**Comment by Neustradamus** [comment]
@Toons33: Can you sign the CLA of your current PR of the another project? Thanks in advance.

**Comment by pgourlain** [comment]
Hi,

Sorry for the delay.

you can add exclusions, but in your settings.json, in .vscode folder

```
{
...
    "search.exclude" : {
        "**/_build": true
    }
...
}
``` 

navigation is like a "search", so this extension use "search.exclude" vscode settings

**Comment by Toons33** [comment]
Thanks!
