### ISSUE TITLE
Why doesn't `include_lib` work?

### ISSUE THREAD

**Issue by scottming** [pgourlain/vscode_erlang#148]
![image](https://user-images.githubusercontent.com/12830256/75085068-399c7e00-5560-11ea-9c08-e819c5c4c1b8.png)

I'm new to erlang, and following this book: https://learning.oreilly.com/library/view/property-based-testing-with/9781680506556/

I did these commands and found warnings in the upper image.

```sh
$ rebar3 new lib pbt
$ mv ~/pbt pbt-erl
$ cd pbt-erl
$ rebar3 help proper
$ rebar3 new proper foundations
```

This is the test project: https://github.com/scottming/pbt-erl

The command line works well, but dialyzer not.

![image](https://user-images.githubusercontent.com/12830256/75085134-1faf6b00-5561-11ea-8fe7-ad8a7ff072d7.png)

**Comment by tommysanterre** [comment]
I had the same issue, I added the path to my include files in the vscode workspace setting.

{
   "erlang.includePaths": [
    "./source/sxv/app",
    "./source/sxv/lib"
  ]
}

It seems the extension does not read rebar.config include paths.

**Comment by tommysanterre** [comment]
Seems to be related to https://github.com/pgourlain/vscode_erlang/issues/89
