### ISSUE TITLE
Problems with Run/Debug on cowboy 2.7

### ISSUE THREAD

**Issue by cjfpainter** [pgourlain/vscode_erlang#149]
I can run a cowboy server via the Terminal, but if I try to run via F5 or ctrl F5 in VS Code I get errors. Being an Erlang Newb this is likely my incompetence, rather than an issue, can you enlighten me?

Here's the terminal output

chris@chris-Precision-WorkStation-T5400:~/published/arbitron$ rebar3 compile
===> Verifying dependencies...
===> Compiling arbitron
chris@chris-Precision-WorkStation-T5400:~/published/arbitron$ rebar3 shell
===> Verifying dependencies...
===> Compiling arbitron
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Eshell V10.7  (abort with ^G)
1> ===> The rebar3 shell is a development tool; to deploy applications in production, consider using releases (http://www.rebar3.org/docs/releases)
launched arbitron 8080.
===> Booted arbitron

Here's the debug window
``
debug:Starting http listener...
debug: on http://127.0.0.1:44965

Starting erlang
	path      : /home/chris/published/arbitron
	arguments : undefined
using erlang binaries from path : '/usr/lib/erlang/bin'
starting : erl 
-noshell -pa "/home/chris/.vscode/extensions/pgourlain.erlang-0.5.2/apps/erlangbridge/ebin" -s int -vscode_port 44965 -s vscode_connection start -args_file "/tmp/arbitron_442080" 
erlang bridge listen on port :48591
arbitron_app:start(a,b)
badmatch: {error,{not_started,crypto}}

Here's the offending code
[cowboyserver.zip](https://github.com/pgourlain/vscode_erlang/files/4426540/cowboyserver.zip)

**Comment by pgourlain** [comment]
Hi,

sorry for the delay....
try start  : erl.exe -s arbitron_app
if you have same error, add crypto:start(), in your app start to ensure crypto is started when you use it

**Comment by cjfpainter** [comment]
more trouble than it's worth
