### ISSUE TITLE
can't debug crash in do_boot

### ISSUE THREAD

**Issue by gnilsson2** [pgourlain/vscode_erlang#152]
{"init termi
init terminating in do_boot ({undef,[{hello,start,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...
nating in do_boot",{undef,[{hello,start,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1109}]},{init,do_boot,3,[{file,"init.erl"},{line,817}]}]}}
done
erl exit code:1
erl exit with code 1
erl exit code:1
erl exit with code 1

**Comment by nerfpops** [comment]
Getting the exact same error

**Comment by pgourlain** [comment]
Hi,

I publish a 0.6.2 today. Can you retry twice :
- configuration erlang.debuggerRunMode set to external
- configuration erlang.debuggerRunMode set to server

from this version, I change the debugging launching to remove all int:ni(...) from -eval command to compile them at debug starts.

**Comment by nerfpops** [comment]
It seems the message is gone, but the debugger still doesn't seem to work.

This is the output:
```
> Executing task in folder learn: rebar3 compile <

===> Verifying dependencies...
===> Compiling learn

Terminal will be reused by tasks, press any key to close it.
```
No breakpoints are reached.

launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch erlang",
      "type": "erlang",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "preLaunchTask": "rebar3 compile"
    }
  ]
}
```

tasks.json:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "rebar3 compile",
      "type": "shell",
      "command": "rebar3 compile",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher" :"$erlang"
    }
  ]
}
```

code base is just a rebar3 new app template.

I have confirmed that I'm using 0.6.2.

Changing debuggerRunMode does not seem to make a difference.

I'm completely new to Erlang, so it's very likely I'm doing something wrong.

**Comment by pgourlain** [comment]
I forgot in my previous message.
you should restart vscode after changing debuggerRunMode.
because this config is read on extension activation.

retry debuggerRunMode = 'server', then restart vscode

I use also Erlang 23.

**Comment by nerfpops** [comment]
Awesome, it works! Thanks for surprisingly fast support.
