### ISSUE TITLE
fun in record definitions breaks record syntax highlighting

### ISSUE THREAD

**Issue by abalazsik** [pgourlain/vscode_erlang#153]
If you define a record which has a field that has a fun type, it will break the syntax highlighting of the upcoming records
![screencap](https://user-images.githubusercontent.com/29358166/84072595-b6e4e500-a9cf-11ea-83c2-37631dd2707f.png)

**Comment by pgourlain** [comment]
Hi,

I think this issue is fixed in 0.6.2, could you check ?
![image](https://user-images.githubusercontent.com/732436/85205205-2507a100-b31a-11ea-95de-b187697fd61e.png)

**Comment by abalazsik** [comment]
Yes, now it is fixed! Thank you!
