### ISSUE TITLE
Debugging not possible with 0.6.2

### ISSUE THREAD

**Issue by obi458** [pgourlain/vscode_erlang#161]
Using https://github.com/PatrickSachs/erlang-vscode-test!

Debugging(0.6.2) does not work, with version 0.5.2 it does!

**Comment by pgourlain** [comment]
Thanks for your report.

could you check this : 
- change  erlang.debuggerRunMode configuration to  'server'
- restart vscode
- try debug

in parallel, I will check with your repo

**Comment by obi458** [comment]
change erlang.debuggerRunMode configuration to 'server' does not work!
btw: Debug Console shows no output, version 0.5.2 does it!

**Comment by obi458** [comment]
Sorry, after restart vscode **it works**!

**Comment by pgourlain** [comment]
no problem,
have a nice day !
because I upgrade to a newest vscode engine and debugeradapter. may be I missed something
I will take a look on this : "Debug Console shows no output"

**Comment by obi458** [comment]
After restarting, Debug Console works, too!
