### ISSUE TITLE
Run without debugging does not work!

### ISSUE THREAD

**Issue by obi458** [pgourlain/vscode_erlang#162]
Using https://github.com/PatrickSachs/erlang-vscode-test!

settings.json:

{
    "erlang.verbose": true,
    "erlang.debuggerRunMode": "server"
}

starting : erlc 
-o /Users/me/.vscode/extensions/pgourlain.erlang-0.6.2/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:62174

Starting erlang
	path      : /Users/me/devel/erlang-vscode-test
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
starting : erl 
-noshell -pa "/Users/me/.vscode/extensions/pgourlain.erlang-0.6.2/_build/default/lib/ebin" -s int -vscode_port 62174 -compiled_args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/bp_163186.erl" -s vscode_connection start -args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/erlang-vscode-test_163186" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/bp_163186.erl: no such file or directory
{"init terminating in do_boot",{{badmatch,error},[{vscode_connection,compile_argumentsfile,0,[{file,"vscode_connection.erl"},{line,24}]},{vscode_connection,start,0,[{file,"vscode_connection.erl"},{line,12}]},{init,start_em,1,[]},{init,do_boot,3,[]}]
}}
init terminating in do_boot ({{badmatch,error},[{vscode_connection,compile_argumentsfile,0,[{_},{_}]},{vscode_connection,start,0,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
Crash dump is being written to: erl_crash.dump...
done
erl exit code:1
erl exit with code 1
******** Error in DebugAdapter - uncaughtException: Error: ENOENT: no such file or directory, unlink '/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/bp_163186.erl'

**Comment by pgourlain** [comment]
Hi,

Thanks for your report.

I didn't reproduce as is, but i'll add some debug log to understandard why your 'bp_163186.erl' is not created before starting debugger

My report with same repo :
using erlang binaries from path : '/Users/pgo/Library/Application Support/ErlangInstaller/20.2/bin'
starting : erlc 
-o /Users/pgo/Documents/sources/vscode_erlang/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:59288

Starting erlang
	path      : /Users/pgo/Documents/sources/erlang/erlang-vscode-test-master
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
using erlang binaries from path : '/Users/pgo/Library/Application Support/ErlangInstaller/20.2/bin'
starting : erl 
-noshell -pa "/Users/pgo/Documents/sources/vscode_erlang/_build/default/lib/ebin" -s int -vscode_port 59288 -compiled_args_file "/var/folders/1f/4jwxgtss7kj17vq1glc98_500000gn/T/bp_5979699.erl" -s vscode_connection start -args_file "/var/folders/1f/4jwxgtss7kj17vq1glc98_500000gn/T/erlang-vscode-test-master_5979699" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"

=PROGRESS REPORT==== 22-Jun-2020::18:53:06 ===
          supervisor: {local,sasl_safe_sup}
             started: [{pid,<0.65.0>},
                       {id,alarm_handler},
                       {mfargs,{alarm_handler,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,2000},
                       {child_type,worker}]

**Comment by pgourlain** [comment]
Hi,

I found the problem. I'l fix asap.
thanks again for your detailled report !
