### ISSUE TITLE
Run without debugging prevents further debugging!

### ISSUE THREAD

**Issue by obi458** [pgourlain/vscode_erlang#164]
Using https://github.com/PatrickSachs/erlang-vscode-test!

settings.json:

{
"erlang.verbose": true,
"erlang.debuggerRunMode": "server"
}

Does not work means, no stop on debug points!

a)
1) Run without debugging, works
2) Start **debugging, does not work!**

Restart vscode!

b) 
1) Start debugging works
2) Run without debugging works
3) Start **debugging, does not work!**

Logs:

**a)
1)Run without debugging**
starting : erlc 
-o /Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:49981

Starting erlang
	path      : /Users/me/devel/erlang-vscode-test
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
starting : erl 
-noshell -pa "/Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin" -s int -vscode_port 49981 -s vscode_connection start -args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/erlang-vscode-test_6148759" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
Running the code!
erlang bridge listen on port :49984

**2)Start debugging**
starting : erlc 
-o /Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:49996

Starting erlang
	path      : /Users/me/devel/erlang-vscode-test
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
starting : erl 
-noshell -pa "/Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin" -s int -vscode_port 49996 -s vscode_connection start -args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/erlang-vscode-test_190473" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
Running the code!
erlang bridge listen on port :49999

**b) 
1)Start debugging**
starting : erlc 
-o /Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:49899

Starting erlang
	path      : /Users/me/devel/erlang-vscode-test
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
erl file '/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/bp_4786282.erl' was generated with content : -->
-module(bp_4786282).
-export([configure/0]).

configure() -> 
 int:start()
,int:ni("/Users/me/devel/erlang-vscode-test/src/erlvscode_app.erl")
,int:ni("/Users/me/devel/erlang-vscode-test/src/erlvscode_sup.erl")
,int:break(erlvscode_app, 18)
,int:break(erlvscode_app, 30)
,int:break(erlvscode_app, 32)
,ok.
<--
starting : erl 
-noshell -pa "/Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin" -s int -vscode_port 49899 -compiled_args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/bp_4786282.erl" -s vscode_connection start -args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/erlang-vscode-test_4786282" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
erlang bridge listen on port :49902
Running the code!

**2)Run without debugging**
starting : erlc 
-o /Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:49938

Starting erlang
	path      : /Users/me/devel/erlang-vscode-test
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
starting : erl 
-noshell -pa "/Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin" -s int -vscode_port 49938 -s vscode_connection start -args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/erlang-vscode-test_1319843" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
Running the code!
erlang bridge listen on port :49941

**3)Start debugging**
starting : erlc 
-o /Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin gen_connection.erl vscode_connection.erl vscode_jsone.erl
vscode_connection.erl:2: Warning: behaviour gen_connection undefined
erlc exit code:0
debug:Starting http listener...
debug: on http://127.0.0.1:49948

Starting erlang
	path      : /Users/me/devel/erlang-vscode-test
	arguments : -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
starting : erl 
-noshell -pa "/Users/me/.vscode/extensions/pgourlain.erlang-0.6.3/_build/default/lib/ebin" -s int -vscode_port 49948 -s vscode_connection start -args_file "/var/folders/pm/92nf75zx0z900hjrlmg4g55w0000gn/T/erlang-vscode-test_2543068" -env ERL_LIBS ./_build/default/lib -setcookie dev -sname dev -config ./config/sys.config -eval "application:ensure_all_started(erlvscode)"
Running the code!
erlang bridge listen on port :49951

**Comment by pgourlain** [comment]
Hi,

thanks for your detailled report.
 right now, i don't know why, the launchRequestArgument provided by DebugProtocol framework send to me always 
noDebug: true, after the first starts without debugging.

/** Arguments for 'launch' request. Additional attributes are implementation specific. */
    interface LaunchRequestArguments {
        /** If noDebug is true the launch request should launch the program without enabling debugging. */
        noDebug?: boolean;
...

I'll try to find where this argmuent is set

**Comment by PatrickSachs** [comment]
Hello @pgourlain - What's the status on this? DId you have some time to look at it? Thanks for your time!

**Comment by pgourlain** [comment]
Hi,

Same status, I did not found why vscode send always to my code "noDebug" : false, after the first launch without debugger

**Comment by obi458** [comment]
Hi,

i found this, which sounds strange: https://code.visualstudio.com/updates/v1_47

New API for Run without Debugging#
VS Code's "Run without Debugging" feature is a variant of debugging where an existing debug configuration is reused for running a program instead of debugging it. A consequence of this run mode is that the program does not break into the debugger, neither for hitting breakpoints nor for any other reason.

In this milestone we provide official extension API for "Run without Debugging": a new property noDebug has been added to the DebugSessionOptions of the debug.startDebugging function. noDebug controls whether the session about to start should run with or without debugging. When the noDebug property is missing, the value from the parent session (if there is one) is used. If there is no parent session, the value 'false' is assumed for a missing noDebug property.

Please note: Previously it was possible to add a noDebug flag to a launch configuration to achieve the same effect. This unofficial API is now deprecated (but still supported) and we suggest that extensions transition to the new API.

**Comment by obi458** [comment]
With the VSCode June update it seems now to work!

**Comment by pgourlain** [comment]
Thanks, I will update

**Comment by PatrickSachs** [comment]
I can confirm this, works for me too.

**Comment by pgourlain** [comment]
Thanks for your feedbacks
