### ISSUE TITLE
Changelog doesn't appear in the correct place when browsing the extension

### ISSUE THREAD

**Issue by asampal** [pgourlain/vscode_erlang#17]
I'm not sure why your changes don't appear in the "Changelog" section in VSCode since CHANGELOG.md is at the root of the project where it should be, but it seems something is not quite right. I almost missed the changes because right now they end up at the end of the "Details" section when you browse the extension. Nothing appears in the "Changelog" section.

**Comment by pgourlain** [comment]
Yes, you are right !
When I published the last release, I saw the same thing then I decided to know what I miss in order to see "changelog" in the correct tab. So I push Changelog.md in my repo after publishing last release.
It should be correct in next release.
