### ISSUE TITLE
Sharing grammar with Erlang LS

### ISSUE THREAD

**Issue by robertoaloi** [pgourlain/vscode_erlang#181]
Hi,

As part of the Erlang LS VS Code extension we use a fork of the TextMate Erlang bundle and I can see you do the same.
I put the grammar into a separate repo:

https://github.com/erlang-ls/grammar

I can see that your version already contains a number of useful improvements over the original grammar:

https://github.com/pgourlain/vscode_erlang/blob/master/syntaxes/erlang.tmLanguage
https://github.com/textmate/erlang.tmbundle/blob/master/Syntaxes/Erlang.plist

I wonder if you are interested in using a common grammar (probably as a submodule) for both extensions, to avoid duplication.

**Comment by pgourlain** [comment]
Hi @robertoaloi,

Sorry about the delay. I make this extension only on my free time...

Nice idea. I will add it as submodule.

**Comment by robertoaloi** [comment]
Feel free to include your improvements in the common grammar, then. I can share ownership of that repo, if you want.
