### ISSUE TITLE
Spaces Are Not Escaped in the Path to Rebar3

### ISSUE THREAD

**Issue by Hypro999** [pgourlain/vscode_erlang#182]
It seems like this extension does not quote (nor escape spaces in) the path to rebar3. This causes errors such as the one below:

```
erlang extension is active
starting : escript.exe 
c:\Users\Hemanth V. Alluri\.vscode\extensions\pgourlain.erlang-0.6.7\rebar3 compile
escript: Failed to open file: c:\Users\Hemanth
escript.exe exit code:1
starting : erl 
-noshell -pa src -pa ebin -s int -vscode_port 33765 -s vscode_lsp_entry start 33765 
spawn C:\WINDOWS\system32\cmd.exe ENOENT
ensure 'erl' is in your path.
```

On Linux this generally isn't as common of an issue since rebar3 would most commonly be found at `/usr/bin/rebar3` or something, but on Windows rebar3 would generally be installed in "c:\Program Files\..." or in the user's home directory like above - where the user's full name with spaces is used.

**Comment by Hypro999** [comment]
Now, I'm currently not really well versed with how to write a vscode extension, but it seems like the issue is in `lib/RebarShell.ts`. Notably the [results](https://github.com/pgourlain/vscode_erlang/blob/9b3283d630957e15c0ef21b4a30015cecc8b6cd4/lib/RebarShell.ts#L38) of `getRebarFullPath` are not accounting for spaces.

**Comment by pgourlain** [comment]
Hi,

Thanks for your report. I will fix it.

**Comment by Hypro999** [comment]
Thanks for fixing this! I appreciate the work.
