### ISSUE TITLE
Go to definition stopped working

### ISSUE THREAD

**Issue by wojteksurowka** [pgourlain/vscode_erlang#195]
Version 0.7.1 broke Go to definition functionality. Few times it worked for me but in most cases it shows "No definition found for...". I checked for function calls, records and macros. Even in a simple case when I have a not exported function which calls itself recursively, when I try to go to its definition from the recursive call it shows "No definition found".
I confirmed that after downgrading to 0.7.0 the problem disappears.

**Comment by shuying2244** [comment]
Hello, can you provide an example

**Comment by wojteksurowka** [comment]
Use OTP sources. I opened otp_master directory in VSC and opened the file lib/inets/src/http_client/httpc_handler.erl line 252 with `do_handle_call` call. In 0.7.1 it shows No definition found, in 0.7.0 it correctly jumps to line 368.

**Comment by shuying2244** [comment]
My OTP version is 19.3.  
The 0.7.1 of the plugin works fine on my computer.  

![temp](https://user-images.githubusercontent.com/40920095/114300388-abcc7b00-9af2-11eb-9743-f2f401b8d5fd.gif)

**Comment by wojteksurowka** [comment]
I cloned otp repository just before making this test, you tried on an older so different version. In my own projects in 0.7.1 go to definition works maybe 1 out of 20 tries, while in 0.7.0 it was working each time. 
The Erlang version I use is 23.

**Comment by pgourlain** [comment]
Hi @wojteksurowka,

Thanks for your report.
I can reproduce when I switch to Erlang 23.

**Comment by pgourlain** [comment]
Hi,

I just publish a quick fix (0.72). I will analyze deeper after.

**Comment by wojteksurowka** [comment]
I confirm that 0.7.2 fixes the issue I saw, and also Go To Definition seems to be working in more cases. Thank you!
