### ISSUE TITLE
no auto indenting?

### ISSUE THREAD

**Issue by 7stud** [pgourlain/vscode_erlang#2]
Indenting doesn't seem to work. When I type:

`myFunc(X) ->  `

and hit return, the cursor ends up under the 'm', rather than indented some amount:

<img width="981" alt="erl copy" src="https://cloud.githubusercontent.com/assets/891276/22396450/fb43e8bc-e516-11e6-98f8-bdd39aad8638.png">

```
VS Code 1.8.1
Mac OSX 10.10.5
$ erl -v
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V6.4  (abort with ^G)
```

**Comment by pgourlain** [comment]
Hi,

I have only implemented "syntax highlighting".  I made this extension on my free time (I would like more ;-))
I think is a great feature to increase developer productivity.

**Comment by shezarkhani** [comment]
This works for me. close?

**Comment by pgourlain** [comment]
I don't think so. For me it doesn't on Windows

**Comment by pgourlain** [comment]
Hi @7stud,

@wojteksurowka pushed #65 that implements auto indent, could you check ?

Let me know if it works to close this issue.

**Comment by wojteksurowka** [comment]
The auto indent is implemented now and the issue can be closed.
