### ISSUE TITLE
0.7.3 broke Run

### ISSUE THREAD

**Issue by wojteksurowka** [pgourlain/vscode_erlang#201]
With the new versions with webpack - 0.7.3 and 0.7.4 - I cannot run without debugging or start debugger. The commands Run Without Debugging and Start Debugging show the following error:

Launching debugger throw an error : Erlang compile failed : Error: ENOENT: no such file or directory, mkdir '\_build\default\lib\ebin'

Reverting to version 0.7.2 fixes the problem. My project uses rebar3, launch.json has one configuration using "erlang" launch type, I use Erlang/OTP 23. 

If I debug the extension with the current sources so it opens the second VSC there is no problem and everything works as before. But if I use the extension installed normally from VSC marketplace the error happens.

**Comment by shuying2244** [comment]
Hello, I can not use the debugging function when I updated to 0.7.4. It is normal when 0.7.2. The following is the error message:

**Comment by ShraikRu** [comment]
Hello! Cant run application with debugger. Error: Erlang compile failed: Error: ENOENT: no such file or directory, mkdir "'_build\default\lib\ebin"

**Comment by pgourlain** [comment]
Hi,

Thanks for yours report.
I didn't have it on my mac, but i reproduce on windows OS.

I'll fix it asap.

**Comment by wojteksurowka** [comment]
Thank you for quick fix!

**Comment by shuying2244** [comment]
Thank you!
