### ISSUE TITLE
go to function definition stopped working

### ISSUE THREAD

**Issue by IgorKoshnarov** [pgourlain/vscode_erlang#225]
After update to v.0.8.3 version "go to function definition" functionality stopped working.
Currently to solve the problem I rolled back to version v.0.8.2 of the extension.
On start of v.0.8.3 I get error:
`apps/erlangbridge/src/vscode_erlfmt_scan.erl:350: function map_get/2 undefined`

**Comment by wojteksurowka** [comment]
Which Erlang/OTP version are you using?

**Comment by IgorKoshnarov** [comment]
Erlang/OTP 20.3

**Comment by brianhu-tw** [comment]
I got the same issue, but I'm using `Erlang/OTP 23.3.4.5`
The `v0.8.4` worked for me, but this error happened if I upgrade to `v0.8.5` or `v0.8.6`.

```
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
escript exit code:127
starting : erl 
-noshell -pa src -pa ebin -s int -vscode_port 53169 -s vscode_lsp_entry start 53169 
spawn /bin/sh ENOENT
```

**Comment by wojteksurowka** [comment]
This happens due to mismatch between your older Erlang version and rebar3 included in the extension. Go to extension settings and set rebar path to the location of rebar3 which works with your Erlang setup. This should solve the problem.
