### ISSUE TITLE
lsp_handlers.erl:160: function formatting/1 undefined

### ISSUE THREAD

**Issue by hengzheng** [pgourlain/vscode_erlang#226]
When I open the vscode，I get error msg like this:
![image](https://user-images.githubusercontent.com/22463559/149448954-c632c4d1-9077-4d77-a15c-c709b342502a.png)
Is it missing dot(".") after "-endif" and "-else" in apps/erlangbridge/src/lsp_handler.erl?
![image](https://user-images.githubusercontent.com/22463559/149448440-80b01cd1-f484-4289-adff-dd621d5917fc.png)

**Comment by MiguelERuiz** [comment]
Hi @hengzheng I have the same error as you and it looks like that, there is a missing dot "." on that line

**Comment by MiguelERuiz** [comment]
Hi @pgourlain with this fix now I can navigate through the code. Thank you so much!! Regards.
