### ISSUE TITLE
After update to v.0.8.6 version language server stopped working

### ISSUE THREAD

**Issue by snakeduse** [pgourlain/vscode_erlang#238]
Hello!

After update to version 0.8.6 language server stopped working.
![image](https://user-images.githubusercontent.com/671928/184379979-09b665a6-d49b-4cfa-b4c5-e394514cfae8.png)

I was check it on Deban 10 Buster and Windows 10.
I have Erlang/OTP 23.0 on my machines.

**Comment by wojteksurowka** [comment]
The extension will not work with OTP versions < 24 out of the box anymore due to the upgrade of rebar3 included in the extension. The workaround which should work for you: in VSC settings set Rebar Path to the directory containing rebar3 which works with your Erlang version.

**Comment by snakeduse** [comment]
@wojteksurowka Thank you for the information!
