### ISSUE TITLE
Extension doesn't allow me to add dependency

### ISSUE THREAD

**Issue by meppu** [pgourlain/vscode_erlang#254]
> :warning: This can be a stupid post!

As an Elixir programmer, i am currently learning Erlang to both increase my knowledge about BEAM and for implementing my libraries to Erlang so they can be used in another BEAM languages like Elixir or Gleam easier. (some Erlang programmers would want to avoid using any Elixir libraries because Elixir needs to include it's standard library at runtime)

Anyways, so i installed the extension, created a new rebar3 project, and now i want to add a dependency to `rebar.config` and run `rebar3 compile`. 

But the problem is when i add the dependency to `rebar.config` it removes it automatically. Here is an example:
![error](https://i.imgur.com/NGvCRbN.gif)

If i add dependency from another text editor and then run `rebar3 compile`, it no longer deletes.

**Comment by wojteksurowka** [comment]
I do not think the Erlang extension has any code which modifies rebar.config file in any way. It only reads from this file. Can you double check the language used to edit rebar.config please? Normally it is displayed in the right side of the status bar.

**Comment by meppu** [comment]
It is set as "Erlang", Also tried to close "Format on Close" but it is same. And the same problem also exists for when trying to delete a dependency or adding/removing an application to `<module>.app.src`.

Here is the video (the GIF was ~90mb so i uploaded it to another website): https://streamable.com/5ppi8j

**Comment by wojteksurowka** [comment]
Can you try to change the language to Properties instead of Erlang and see if it helps?

**Comment by meppu** [comment]
Yeah it loses the syntax highlight but now it works!

**Comment by wojteksurowka** [comment]
Ok thanks. I will try to fix the issue, for now you can use Properties as a workaround.

**Comment by wojteksurowka** [comment]
Fixed by #257
