### ISSUE TITLE
not found _build

### ISSUE THREAD

**Issue by liuyanhang2004** [pgourlain/vscode_erlang#269]
![Snipaste_2023-07-14_15-15-34](https://github.com/pgourlain/vscode_erlang/assets/106688439/61fafb73-9763-4aa6-a276-d73a737963b8)

**Comment by liuyanhang2004** [comment]
Start VSCode as an administrator

**Comment by alievfe** [comment]
I also start as administrator but I still have the same problem as your picture, have you made any other changes?😥

**Comment by liuyanhang2004** [comment]
> I also start as administrator but I still have the same problem as your picture, have you made any other changes?😥

basic project configuration
![Uploading Snipaste_23hsyyu3248gqwa8873jqhw2.png…]()

**Comment by liuyanhang2004** [comment]
> I also start as administrator but I still have the same problem as your picture, have you made any other changes?😥
basic project configuration
![Snipaste_981ac2a9-79e8-45d6-af49-a58d45a45bd4](https://github.com/pgourlain/vscode_erlang/assets/106688439/981ac2a9-79e8-45d6-af49-a58d45a45bd4)

**Comment by liuyanhang2004** [comment]
> I also start as administrator but I still have the same problem as your picture, have you made any other changes?😥
basic project config
execute rebar3 compile before running
![AppIcon](https://github-production-user-asset-6210df.s3.amazonaws.com/106688439/274210887-981ac2a9-79e8-45d6-af49-a58d45a45bd4.png)
