### ISSUE TITLE
consider publishing to the Open VSX Registry

### ISSUE THREAD

**Issue by thomasdziedzic** [pgourlain/vscode_erlang#283]
I recently migrated from windows to archlinux.
One of the first things I installed was an [opensource build of vscode](https://archlinux.org/packages/extra/x86_64/code/).
The first thing I did was search for the erlang plugin but to my surprise, I didn't see it, although I did see elixir there so I installed it.
I finished investigating why I'm not seeing erlang, and this is because the default registry on archlinux for the code package is OpenVSX.
The explanation can be found at https://wiki.archlinux.org/title/Visual_Studio_Code#Extensions_support but the tldr is that it's against the terms of service to use microsoft's registry with only microsoft's vscode builds.

Thanks for your time.

**Comment by pgourlain** [comment]
Hi Thomas,

Thanks for your report. I will take a look.

Regards.

**Comment by pgourlain** [comment]
Hi Thomas,

a version is published : https://open-vsx.org/extension/pgourlain92/erlang
I'm trying to claim the 'pgourlain' namespace. So in the meantime I publish on 'pgourlain92'

**Comment by thomasdziedzic** [comment]
Thanks for uploading to the openvsx registry so quickly! I was able to install your erlang extension successfully!
