### ISSUE TITLE
Doesn't highlight the syntax of config files like sys.config, sys.config.src, elvis.config, etc

### ISSUE THREAD

**Issue by amarBitMan** [pgourlain/vscode_erlang#289]

**Comment by amarBitMan** [comment]
@pgourlain  Can you help,  please ??
Is it some config issue ??
my project directory structure looks like this ->
```
.
├── Dockerfile
├── LICENSE
├── README.md
├── dockerz.sh
├── priv
│   └── sys.config
├── rebar.config
├── rebar.lock
└── src
    ├── erl_lite.app.src
    ├── erl_lite_app.erl
    ├── erl_lite_sup.erl
```
The syntax of priv/sys.config doesn't get highlighted. PFA the screenshot ->
![Screenshot 2024-05-13 at 3 17 30 PM](https://github.com/pgourlain/vscode_erlang/assets/34544473/c25778ee-c75c-4812-b3ee-062fc09a3185)

**Comment by pgourlain** [comment]
Hi Amar,

Thanks for your report.
today vscode activate erlang language base on file extensions, and configuration is store in package.json
```json
"extensions": [
					".erl",
					".hrl",
					".xrl",
					".yrl",
					".es",
					".escript",
					".app.src",
					"rebar.config"
				],
```

so yes today, highlight only works for rebar.config 

but you can add in your settings.json => vscode settings
goto vscode settings, then switch to json and add the following lines (customize it as you want)

```json
    "files.associations": {
        "sys.config" : "erlang"
    },
```

**Comment by pgourlain** [comment]
Hi Amar,

can you close this issue, if it solved for you ?
