### ISSUE TITLE
Linter shows false errors

### ISSUE THREAD

**Issue by wojteksurowka** [pgourlain/vscode_erlang#295]
The recent change in linter made linting unusable to me.

Behaviour before change: linter was showing real errors in the current file only, and it was showing them online immediately updating after editing changes

Behaviour after change: linter shows nothing for a file with a syntax error. Then after some minutes it shows the error and bunch of false errors "function module:function/N is missing in export" while the reported functions are not missing and are exported.

I normally rely on dialyzer to check for missing exports, my suspicion is that the size of my project makes the equivalent check in linter not working for me, and as a side effect it made linting not working for me at all, which is painful. I understand the value of missing exports in linting in smaller projects, but could we have an option in settings to control this, so I can disable the new rules and have linting working for me again?

Note that if the option is set to check missing exports by default, anyone trying the extension for the first time on a real project may say "linting is supposed to work, but does nothing".

I confirmed that reverting to 1.0.4 fixes the problem.

**Comment by wojteksurowka** [comment]
Normally I would work on such stuff myself but I have a hectic time at work and zero time for other stuff like the extension. I hope it will change soon, but it did not yet.  And I use the extension for work so any regression like this is a huge problem...

**Comment by pgourlain** [comment]
HI Wojtek,

My goals:
1) is to avoid launch dialyzer on whole projet et quickly show by linting common errors.
2) add "code action" to have quick fix, that generate exports in one clic during development

So it seems has a bad effect on big project. I will deactivate It and review my work by a different way.
