### ISSUE TITLE
Syntax highlighting wrong after fun() without end

### ISSUE THREAD

**Issue by Mikaka27** [pgourlain/vscode_erlang#297]
It seems that syntax highlighting is wrong after type specification that looks like:
`-type ct_info_timetrap_fun() :: fun().`

The problem is `fun()` without `end.`

Steps to reproduce:
1. git clone git@github.com:erlang/otp.git
2. Open vscode on otp folder
3. Open lib/common_test/src/ct_suite.erl in vscode
4. Look at this lines: https://github.com/erlang/otp/blob/master/lib/common_test/src/ct_suite.erl#L82-L83
5. Observe that syntax coloring is wrong after line 82
![image](https://github.com/pgourlain/vscode_erlang/assets/9214100/8177cb66-d5df-4468-bd22-7438ae733af8)

You can even see that the same issue is displayed on github as well (uses same parser or something??):
https://github.com/erlang/otp/blob/master/lib/common_test/src/ct_suite.erl#L82-L83

**Comment by pgourlain** [comment]
Hi Michal,

Thanks for your report.
