### ISSUE TITLE
Go to declaration not working

### ISSUE THREAD

**Issue by stevepm** [pgourlain/vscode_erlang#3]
I have my keybindings as such:

`{ "key": "cmd+b",                 "command": "editor.action.goToDeclaration" }`

Nothing happens when I cmd+b on a fun or module.

**Comment by pgourlain** [comment]
Hi Steve,

You right, today with in vscode you can implement many features (https://code.visualstudio.com/Docs/languages/overview)
But right now, only "syntax highlighting" is implemented in this vscode extension.

**Comment by fafa6** [comment]
+1. Really need this feature~

**Comment by fafa6** [comment]
Nice work! 
Can I go to the methods declared in dependencies under _build/default/lib? This will be helpful.

**Comment by wojteksurowka** [comment]
Finding functions defined in dependencies located under _build does not work yet. It is planned.

**Comment by wojteksurowka** [comment]
@fafa6 in the version 0.2.9 you should be able to go to definitions in dependencies. Can you confirm please?

**Comment by wojteksurowka** [comment]
The issue is fixed and can be closed.

**Comment by fafa6** [comment]
Verified. It works fine.
