### ISSUE TITLE
No Source from subdirs

### ISSUE THREAD

**Issue by obi458** [pgourlain/vscode_erlang#310]
How to config NOT to use source files from subdirs like

 int:ni("${workspaceRoot}/test/test.erl")

How to exclude dir test?

How to include src dir only?

**Comment by pgourlain** [comment]
Hi,

it depends.
for compilation , use rebar and rebar.config  a sample, you take a look here: https://github.com/erlang/rebar3/blob/main/rebar.config.sample

for sources analysis, path are read from rebar.config and today you can add other 'include paths' (not exclude) in vs code Settings => "Include paths" section in Erlang extension configuration
