### ISSUE TITLE
Feed on the include folder when opening a folder with the usual structure (src, include)

### ISSUE THREAD

**Issue by FrankBro** [pgourlain/vscode_erlang#34]
As of 0.18, it seems like the plugin won't feed on the include folder. I get this error:

[ex] {include,file,"rtb_boolean.hrl"}

Which leads to a lot of the source code giving errors. I think it used to feed on that folder so possibly the introduction of new features does not support this yet? I'm fairly new to erlang but I know I can build using rebar3 successfully from the same folder vscode is opened from.

**Comment by pgourlain** [comment]
You right, I plug a linter, but there is a problem with includes. I will fix it

**Comment by arturo-salinas** [comment]
Is this issue fixed? thanks

**Comment by pgourlain** [comment]
Yes, partially.

Because linter doesn’t use rebar configuration, so in some cases (when include is not fully specified) code giving errors.

**Comment by wojteksurowka** [comment]
Linter now uses rebar configuration. The issue can be closed.
