### ISSUE TITLE
Valid include_lib call appears as an error

### ISSUE THREAD

**Issue by uhaciogullari** [pgourlain/vscode_erlang#35]
Hi Pierrick,

Thanks for your great work on this extension. New error highlighting looks really great.

I have a small problem with including a library.
![screenshot from 2018-03-05 15-32-46](https://user-images.githubusercontent.com/1431130/37005908-19cba2ba-20d6-11e8-976d-007c7f4beaf4.png)
This module can be compiled but it looks like an error. Every reference to a record from this library also appears as an error. 

I ran `rebar3 dialyzer` and it didn't output any warnings for these lines.  Do you have any idea what could be the cause? Let me know if you need more information.

Kind regards

**Comment by pgourlain** [comment]
Thanks for your feed back !

And yes I have an idea, I use 'epp:parse_file', without any specification about include path...

**Comment by uhaciogullari** [comment]
This is fixed. Thanks a lot Pierrick.

**Comment by Katur7** [comment]
@uhaciogullari, I am having the same issue. I don't understand what you did do fix the issue, can you explain what you did to fix it?

**Comment by uhaciogullari** [comment]
I didn’t do anything really. I thought one of the updates fixed it.
