### ISSUE TITLE
use rebar3 instead of rebar

### ISSUE THREAD

**Issue by vladdu** [pgourlain/vscode_erlang#4]
'rebar' is now deprecated, rebar3 is the current version

**Comment by NobbZ** [comment]
It seems as if `rebar3` is used, but it is searched for in my project folder instead of in my PATH...

**Comment by vladdu** [comment]
Yes, it looks like it was addressed, but with the assumption that there is a `rebar` or `rebar3` script at the root of the project. While that is common, sometimes it is in the $PATH too. 

The question then becomes how to know which one to use if the $PATH contains both `rebar` and `rebar3`...

**Comment by NobbZ** [comment]
Workspace configuration, magical comment in rebar configuration, prefer rebar3… Plenty of options…

**Comment by vladdu** [comment]
Maybe we can use rebar3 by default and use a setting to override that, if the user needs it.

**Comment by benoitc** [comment]
issue should be closed probably :)
