### ISSUE TITLE
Erlang language server node is never stopped

### ISSUE THREAD

**Issue by radupopescu** [pgourlain/vscode_erlang#57]
Hi,

First of all, thanks for making this plugin!

I've noticed a problem...

Every time I open an Erlang project, a new Erlang node is spawned These nodes are never stopped. For example, after opening and closing the same project three times, I see:

```
 ps aux | grep beam
radu     18270  0.2  0.0 4109356 26696 ?       Sl   16:37   0:00 /usr/lib/erlang/erts-9.3/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/radu -- -kernel shell_history enabled -noshell -pa src -pa ebin -s int -vscode_port 35683 -s vscode_lsp_entry start 35683
radu     18912  1.4  0.0 4106028 26864 ?       Sl   16:39   0:00 /usr/lib/erlang/erts-9.3/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/radu -- -kernel shell_history enabled -noshell -pa src -pa ebin -s int -vscode_port 34532 -s vscode_lsp_entry start 34532
radu     19203 13.6  0.0 4117420 31760 ?       Sl   16:39   0:00 /usr/lib/erlang/erts-9.3/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/radu -- -kernel shell_history enabled -noshell -pa src -pa ebin -s int -vscode_port 42898 -s vscode_lsp_entry start 42898
```

The Erlang process persists both when I close the editor completely or when I use "Close Folder" in VSCode.

I've noticed this on a Linux workstation, but I can also check on a Macbook, to see if it happens.

**Comment by wojteksurowka** [comment]
It may be result of some of the changes in debugging support I did. I will look into it.

**Comment by wojteksurowka** [comment]
@radupopescu it should be fixed in 0.3.0. Can you confirm please?

**Comment by radupopescu** [comment]
@wojteksurowka I checked 0.3.0 on my Macbook and the issue seems to be fixed.

Tomorrow, I can also check on my Linux workstation, if needed.

Thanks!

**Comment by wojteksurowka** [comment]
@radupopescu Confirm that there is no problem on Linux and then close the issue please - thank you!

**Comment by radupopescu** [comment]
Tested version 0.3.0 on Linux, works great. Thanks again for the quick fix!
