### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by shian** [pgourlain/vscode_erlang#69]
Hi

I has a project that file structure is like below.
It split different services into different applications. Each application has its rebar.config.
But current vscode_erlang only read rebar.config in top folder.
Does vscode_erlang support file structure like this ?

```
    $PROJECT_ROOT
     |
     -- rebar.config
     -- apps/            % Contains all applications which are
          |              % part of the system.
          |   
          | -- some_app/
          |         |
          |         -- rebar.config
          | -- another_app/
                     |
                     -- rebar.config
```

**Comment by wojteksurowka** [comment]
@shian 
Only the top level rebar.config is used now. Can you try to use erlang.includePaths setting to see if this can help please? Relative paths can be used there.

**Comment by shian** [comment]
Hi 

Relative paths seem not work.
I set "./apps"  or "../../" or "../../../apps" but it still got error "can't find include lib"
Using absolute path is ok  "$PROJECT_ROOT/apps", compile without error

**Comment by wojteksurowka** [comment]
@shian Have you tried just "apps" ?

**Comment by shian** [comment]
Confirm that it can set relative path in setting with version 0.3.3

But it do not add "some_app/include" into include path.
So still got error with "-include()'

**Comment by shian** [comment]
Hi

My project structure is similar to https://github.com/erlang/sourcer
Here is steps to reproduce error

1. clone https://github.com/erlang/sourcer to local
2. create new window and open sourcer folder in VS Code
3. open file: apps/sourcer/src/sourcer_db.erl
4. It show error at line 20 with error message "can't find include file"

**Comment by wojteksurowka** [comment]
@shian  Try in 0.3.4 please.

**Comment by shian** [comment]
Confirm it is fixed. Thanks
