### ISSUE TITLE
include path

### ISSUE THREAD

**Issue by shian** [pgourlain/vscode_erlang#70]
Hi

May I ask why put "filename:rootname(File)" in include path ?
I thought it may change to filename:dirname(File) ++ "/../include"

https://github.com/pgourlain/vscode_erlang/blob/bca78afa1d9629a02f657ee3bf837a6a75906abf/apps/erlangbridge/src/lsp_syntax.erl#L66

**Comment by wojteksurowka** [comment]
Look at
http://erlang.org/doc/man/erlc.html

-I <Directory>

    Instructs the compiler to search for include files in the Directory. When encountering an -include or -include_lib directive, the compiler searches for header files in the following directories:

        1. ".", the current working directory of the file server

        2. The base name of the compiled file

        3. The directories specified using option -I; the directory specified last is searched first

The line you quoted is to support the item 2.

**Comment by shian** [comment]
Hi

I see. I never use item 2 before. 
Thanks
