### ISSUE TITLE
string:replace not exist in 18.0

### ISSUE THREAD

**Issue by shian** [pgourlain/vscode_erlang#72]
string:replace() cause error "undef" with OTP 18.0

https://github.com/pgourlain/vscode_erlang/blob/b1025285b4a819f6e5a15c00016b0a9c2344c4ca/apps/erlangbridge/src/hover_doc_layout.erl#L52

**Comment by wojteksurowka** [comment]
Fixed in 0.3.4.

**Comment by shian** [comment]
Confirm it is fixed. Thanks.
