### ISSUE TITLE
Analyzing of code in ifdef?

### ISSUE THREAD

**Issue by pselden** [pgourlain/vscode_erlang#74]
I add eunit tests to the same file like:

```erl
-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").

%% tests here
-endif.
```

However, this extension does not appear to analyze code inside these blocks. Is there a way to enable that?

**Comment by pselden** [comment]
Is there a way to configure this manually? rebar3 when it runs eunit will automatically add the TEST define, it's not specified anywhere in the rebar.config

**Comment by pgourlain** [comment]
You can add 'TEST', in erl_opts attributes like this : {erl_opts, [debug_info, {i, "include"}, {d, 'TEST', true}]}.
