### ISSUE TITLE
filename:basedir() is not exist in OTP 18.0

### ISSUE THREAD

**Issue by shian** [pgourlain/vscode_erlang#82]
filename:basedir() is not exist in OTP 18.0

https://github.com/pgourlain/vscode_erlang/blob/634409df532da67fe266e9bd608ff9a9e08d42fd/apps/erlangbridge/src/lsp_handlers.erl#L222

**Comment by wojteksurowka** [comment]
Fixed in PR #83

**Comment by shian** [comment]
It is work. Thanks
