### ISSUE TITLE
Erlang Language Server: Request textDocument/definition failed.

### ISSUE THREAD

**Issue by pselden** [pgourlain/vscode_erlang#85]
After upgrading to 0.4.0 I get the following error, and nothing lints/highlights/code completes:

Any ideas?

```
[Error - 15:17:24] Request textDocument/definition failed.
  Message: Handler error
  Code: -32001 
```

**Comment by pgourlain** [comment]
Hi @pselden ,

Thanks for your feedback.
Do you test with 0.4.1 ?(many fixes have been integrated). If yes... can you enable trace ?

to enable trace :   "erlang.verbose": true in your usersettings

**Comment by pselden** [comment]
Yes sorry, it's 0.4.1

After enabling verbose tracing I saw lots of stuff in the log, and occasionally the codelens would pop up, but even after typing an obvious syntax error nothing would have red squiggles.

Here is a bunch of log output that was generated after I created a new file "test.erl" and then added the following:

```
-module(test).

-import()
```

https://gist.github.com/pselden/5d9518ec936e9aa22b27b17be1db3a25

**Comment by pselden** [comment]
I'm using OTP 20 on OSX Sierra.

**Comment by pgourlain** [comment]
Thanks !

**Comment by pselden** [comment]
Awesome, the syntax highlighting is back, thank you!

**Comment by pgourlain** [comment]
Great !
