### ISSUE TITLE
go to symbol in file

### ISSUE THREAD

**Issue by SergejJurecko** [pgourlain/vscode_erlang#90]
Is this functionality planned any time in the near future? Some of us cant live without it.

**Comment by wojteksurowka** [comment]
@SergejJurecko can you tell us what exactly do you mean by go to symbol in file? It works right now for some source elements like variables. What is the case which is missing and needed by you?

**Comment by wojteksurowka** [comment]
@SergejJurecko What happens if you right click a local function call and select Go To Definition?

**Comment by SergejJurecko** [comment]
That works fine.

**Comment by wojteksurowka** [comment]
@SergejJurecko ok thanks I will look into adding this to symbols list soon.

**Comment by DavidZhiXing** [comment]
On Ubuntu 16.04 ,   right click , not the Go To Definition and other menu

**Comment by SergejJurecko** [comment]
Thank you very much for implementing this.
